# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Learning Linear Algebra using Python
email: bryan@bryan.blog
description: >- # this means to ignore newlines until "baseurl:"
  Learn linear algebra using Python is a series of guides that provide
  a soft introduction to the concepts behind linear algebra and demonstrated
  using Python.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://linearalgebra.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bryanlparker
github_username:  blparker
github_repo: https://github.com/blparker/learn-linear-algebra

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  - guides

include:
  - _guides

feed:
  collections:
    - guides

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - env
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
